name: VM Strategy 2 (Cloudflare)
on: [workflow_dispatch]
jobs:
  vm:
    runs-on: windows-latest
    steps:
      - run: |
          # RDP ON
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # Cloudflare
          iwr https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
          Start-Process .\cloudflared.exe -ArgumentList "tunnel --url rdp://localhost:3389" -NoNewWindow
          
          Start-Sleep 30
          while($true) { Start-Sleep 60 }